# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_employes
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# PrimeFaces
primefaces.THEME=saga
primefaces.CLIENT_SIDE_VALIDATION=true

# JSF
jakarta.faces.FACELETS_SKIP_COMMENTS=true



